apiVersion: v1
kind: Secret
metadata:
  name: tandoor-secret
stringData:
  #ENC[AES256_GCM,data:WSMzbMo4wnU=,iv:IVvT9XdLgtZoLg/nLB9DwOBNR59fXhxtyop4Dsnhawo=,tag:nPVybhp9MpxvSlo7pBxPjg==,type:comment]
  SECRET_KEY: ENC[AES256_GCM,data:UAbkSMIUxrVf8IF7O64sZmcFi0eNK/Tu6FTSTqo+BjVFXXPPBj0E5zFcpNWrDvfuT8M=,iv:SuPKXgrvEfMrKeE0NLT9Du4V7/GqsNowdxND47rRH/M=,tag:Zr8AIMVxHBrPRWe7Cc7CYw==,type:str]
  #ENC[AES256_GCM,data:pzxLW7NAeYsU,iv:kR/Pcu/9ZWQPzMWpqSav3fCTBua4Ss9BcU//f3ePHs0=,tag:hBfPTkQO3NV9CQ+ihf53Kw==,type:comment]
  DB_ENGINE: ENC[AES256_GCM,data:tEZoQG23ys5vdrjiYg+tGkT2gzE6bfz2lrK/rtw=,iv:njcpbKddXDifZVGvDBlcdveaMGyllsttEMQJQzRUDlA=,tag:SyTf62ZfQi276/hFkHoBVA==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:5UyhyxNwB0V/dsv36Z0FPcNtWIwCYiJGszSZBT6y8z9uzBsCvUU=,iv:TgULc1kIVNGGQ5Zpe+wxqjwIC0iOU7jk091ylgToOC8=,tag:1nnIwZNupocu/bvH9Qyq8w==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:JSptIg==,iv:53gM/QMaTIfjkVInTj0c3datvzbHRY1L4KOLN2vvjx0=,tag:zDx2QAOZEYwqGXPHdcx30w==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:hDUgwfwhVg==,iv:CTsvDMI5rAlJxR488kqPW5qS5IarqcTnIHSybStzkl8=,tag:7QOi1xoLuj7rseXXmiMo5g==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:VeOeRzs3DA==,iv:wkqtg98ezKEqBRHNfPW/srWlPL9Q+zwfbwZNJmInbWc=,tag:/G+6+pOI5yupfaPjYHMq3w==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:JRK35g1LP7louc/3gkx/iA==,iv:pZGEXz4Hau3Rq1ejsPjrfc8uqX7SJp7KNbraOd2pcEk=,tag:YFCkaDGg+pNTZhHsZvrs5A==,type:str]
  #ENC[AES256_GCM,data:tlNuf4qaPOpG3sp9Lys=,iv:oYrl/s4pKKtBH6Dby8nVYO1hSpABX1/hqs4gFsljWrg=,tag:qsp27HKRBUqJOZBUvecw+A==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:v5tCK+B07Q==,iv:fUtXgMYJ40CEncm9U66nJbPO6vzhZqI5OHQSQ2RDsAs=,tag:WpvjtZtd9hjpeQ7EC7x2PQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:F28yCGi4XmLg0GkaU5bOjwLDZuujrqB7FYJjDkHWTTdTGcztc34=,iv:H63AarZ2++mbaFTAgq9qfQvxfRf0d/Aj2wRkxnz7qrE=,tag:+i0BHCJzmdc7FTgBfWhLeg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:N7qrujsmQA==,iv:U6rz4etm18QRSIufmrdazNk903ZY1jzEuQBzWOct+Cc=,tag:wVOIQ++J5teHTFrJSHZPfw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wiIli2PmmvVlb123Ltx14g==,iv:MPu+UZPEhSFveT1x6bt/TER5vPJ0Kw43ENIbdhzWgnQ=,tag:Z077ApAW9Fehi7CWJmhGRw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:j482Ni3fcvc=,iv:Mau7SSiv5KTwAxfVKkDSWmpDM+owKjOl4kdmnInCCYw=,tag:isZtszB5IzzhxRAhW4BaSg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWGdqbEEzUDVSRzRDd0h4
        aS9oQkpvaEVOdzQ3dDQ0dXI5cXJJdnppamlRCnY0YzZlajBLb3RlZVdESjNMa3BT
        WFg0bXc0NVgra09Sa2wrbEdoLzRDbGcKLS0tIDBiSzAwb0lhejZOYUJQMlJrSjB1
        WFRHTHp1azVTN1NrUjI2T2oyNEtnNUkKsRfpvyfrmzSc+LNovNfIi4CWyOBEHkUM
        f0FRhdqEel1xshBxYTnzt73mUZ2Jf3FA0KntyiGeaNKNGchvbvaQFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T18:40:23Z"
  mac: ENC[AES256_GCM,data:MNmpJj2wDBWgnjNhNOcFEfrkjLhpaWWUjCaxpPVVn6XtmWJlQoCePvViVAn6PDoYebGHNgyFEUh2Uk12W/C0nmnKC7t2YxHKa00XeJRC1ZHKMu7nAv3tD4n2fHmHTUqpyPX9VBCv9EbjizSNjEcVO8nQED7DACm8gLovLdNrRg0=,iv:X74pOb3TBayLm4cDD5VE2yvfxZO48hL3jUhrnj1OFJA=,tag:l4XMUyZBSmMSRQvdQYOrfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
