apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  #ENC[AES256_GCM,data:iy6xBQ==,iv:s37eqQWAtzzFbDl9eD0d3Y955xfzHuRrQfZd4WcZnP8=,tag:FekUlQQckWux9f7M1CUXvQ==,type:comment]
  ADMIN_TOKEN: ENC[AES256_GCM,data:gmuo43++5hlDd5P466SlR0WudiOXT3lSX7Wnz+HunQkFEgjZxOBv8ZKLQ8CmOUp1OoygfhfErqf0BSLsi4/FrA==,iv:N89B4lOkMCQ4oi6mr5Z4EmFevjoTsGfsLGp04dUPUy8=,tag:xih1paJ7Yrxch4qBLwlGPA==,type:str]
  #ENC[AES256_GCM,data:4AZeOjH6WV6J,iv:BASST0WlqJ/VECqeuKFryMLVvKBxFJi8H2vI+Sp0bdM=,tag:bghFLDnvW4a2NFSeoI6rig==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:emkfkcc5HYecAivBxHU2VipHxMMRyHxil/iY1gNxm0jSIZkFdhu9Q6PJWKMnY4srzY/5way+2d3Y6yE/S7RgX/34xeTlKauN5qYKpUdKSZbEP4+MCj5o6NH9YpV+1FwTNBW4Pe9oOyPexVfRqfE+S8t3scqIVJYYnwspP2CAVikboysvoWkN,iv:YSfLmKLOKs+ehmKYaOEsfnbDIMjC01r4OBz7iXXM+5s=,tag:XtKF0wqo6VGX7n6YGwWfew==,type:str]
  #ENC[AES256_GCM,data:a+IT9a4H7UOUT35iCVQ=,iv:aXEvwo7rNkRwvP7OMhla9WR8FMNraKVa3nm91Q4b+w0=,tag:2S1xKRYknbsvpu035ZnPwA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:SsygijCiVOahF2A=,iv:LxVhaVwN+E0iBnWUehUvIU9+bnoWVH0gApSxLy2R4/M=,tag:Afi7wppPK1Lx8KuaaAnW8w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xA75bsJTZPJpsv5exJUCOBwYufp0T/WoFCrvnCGlTIMrpvpQY14=,iv:t4r5t3v6R4iuoxHH0iyA5w+VBVaN7Sv+rLdTqsxX/q8=,tag:VHo+Bv7A9myvPa/29zDqPQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:FnYVa3uBaB6vzeQ=,iv:2hMCX2BR951NsAVzRnBzlM9k10++k3RIeZAhEdkuB3c=,tag:pzHnOtECuiqaD3cyvJnFtg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ebYHQtynpXg0N/5svU81zezfB6cPU3M8fFBXUR3vrwY58gNnEVndeBO3oMG34QIuKlRFJzbw4IBNXOXrvg==,iv:T+H1oYz1tCRw1B+6on+fraazhiOUP/d7NqCqUsM4I+8=,tag:kgdaRoEAxeLSo6MyyumRHA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pb61IkSVMog=,iv:8QriENm9hNo3fYrkVhpljuvcFzTvZHFrxP3ziNGLw6Q=,tag:0LOooD4Ci+KrP9Hk3qmTZg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNTVVcDEzakptbFNlbUVO
        Sld3anQ1RTYwMm53OTh2ZFR2YThDY2lmYmhnCjhlSzlPdDYvV3A0RU81SENtdWVW
        UHhvUDMyNUM1VWZlTStWV01KbWI5NFEKLS0tIHpGZUFsL3JTd1FHOVdKbjFiWE5z
        UmdvNFZuT0ttSlo1K2pFWlhIbzVQcHMKg8G7HxnIbO/E0N0cuYjQsIhXgciRPMdv
        nRXJFL69ctQgs9lpdHBVsbi62fLqvKNEOVmmKIQUf4LbO9vfmcb7Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T20:03:38Z"
  mac: ENC[AES256_GCM,data:q7IxAtvIJ66cHkMs0cxLvS0QnzznMzkkpYjI2wYb6lN6ogppKjMEUsDXkcUe+AA+3mCmDY+WVC1/k6qF/Kxtxh1YXbxi+XuRkWDnjiKPyOK7GwizMuHAOmF9jjMPem61KmJgwV9gvHygN6reSTfyVgezTtuZ1IqdOvXgsvXx1tw=,iv:OKCg2LrgD91uiexRoVuQbv/ffFoAuhIni+0j54XDgF0=,tag:vf3HucNnQYVX5haWj9zUnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
