apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret
stringData:
  #ENC[AES256_GCM,data:7ImjVQ==,iv:6mLmHPNKqGEnt20LU+eXzjVsODYHCnOGXTpOhaTNbB4=,tag:pBuAX1TaaxCVHdbTYZBg7Q==,type:comment]
  ADMIN_TOKEN: ENC[AES256_GCM,data:3+hYAiPh5ZU7g3j4V1t3278gWOGbIzkDTNqsFqNDGHw5tn6M9XRVC5vNJ451A8khR14RG8si8TeDvScmS217rg==,iv:IuXip28xYWDQsVSQNCXGNf8bNoju/l241p3OulKWfHE=,tag:61tdN/CclHeKyPxKcUrKPQ==,type:str]
  #ENC[AES256_GCM,data:z7Cf/52AOw2J,iv:UD+3lhfa0nXQ3lHUnhboQR0J8IyLpRbDONmfbzrPZMw=,tag:Og68CIHmy6Ah5ShO6Hfxig==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:yELVtzw86u9ktYSsnzILlrvxvyTPdD3NXuh6jtiofFLmniEzGKCK9pHBNfCgIuKiLctHZHeiPKyQaUJZGSGVZHrNlGmeWbXhq7dbuJinXOoZ8A6gZ7oqlyH5DJFwP+J0kpDObJlgVZWXrOgKF0quyMbIDtFYecuRA2JIS9MXaPmJ6LGWvqD40JE=,iv:Yiu5893GUmifKEw9vFx+o+FOSJCpZFcntuDUiPYeIow=,tag:qilOy42fBT/1jpULpsS3dg==,type:str]
  #ENC[AES256_GCM,data:EqTrIQyDaA1+PdRw7Gs=,iv:Yt3sf/FZ0IcdgJzijekRYyMxD/NE44jmFQhlhRgt3mY=,tag:LffQOW9kQjafLb7fakY6Yg==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Oy9Q2yA4RXpL3Vc=,iv:JDB3QPzPqq0FfamBRtRKAHeWjjR5bzTuY8c6y5c6utU=,tag:ldV2JXKjWILQyGzQ69UvmQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SSo2APSVLsj2SPCrq3F9vSgChDESLsusxq2PS1GCH7d4nwkm5yE=,iv:nmsQmo5piICS94vuagjPLw7BIyiEYSY63qE39Lt+Occ=,tag:l+y5075Usk4yPdLwdUVYNg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:kHru9XxLExQSlTA=,iv:r1o76yvA55Q6oOZPZ5DDY7qeKMObdW2GkUM33Zhr6S4=,tag:nDm9qZRoww3+66H+Qd/DpQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eqXIKEED7Tl3rNoGl9DuU7/W/SpdrUJyAtMdQk1u5a7Pc112zqFgpvV59757GLnhvD4Murzkfp9jqzU+EsvRPg==,iv:CZKPt+0K6jo3Dol5sZyf8UZ+ThSNxt568+IZTXNOMfg=,tag:1ys8JYKxfZKxqO6SmtiG7Q==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:hA6XsdIb9fE=,iv:0tDRVhORSPPW+1YazbGufCeaj65jU/lXgrBkmKCdn/s=,tag:t6hMyb0eRowdfGEnckvEfQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSG83RDBKVWxLWE00THg2
        MWljRmw3QldnaCtpTm5SV0RFNUZBMmJoZGdvCmExTzdldEg0N2FWNG8wT1pzKzN0
        Zy9zVkZIdFdOaWY1TkNBWk54UGwycWcKLS0tIDlmOU9vbUxPWXBhUFo3VVZBeWRO
        OUxaektZamppeE9pWUxUMDBzaDN6RXcKQqQT04LxhSN/LgAqLABYpcgaUP16wP3h
        x6VLRgd/eMQp4/KBoW1rVQ5oBiHLLG5zpqoXRoI2dqbQxQkOl1+aUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T19:21:53Z"
  mac: ENC[AES256_GCM,data:g8qPasR5lfy24o3hLODZOM8S08nVpuqeSPjDJNe/uUt4Vk2LtpsI29qPBXlrGzhjSyoRuGSdw71z4itREvB1GocsNH2Kc1kNkP/Y3CJeooY6CvkZT+1HjQ+MbcxBq+4h+7FvgX8CuDVH0858q9CVXTVuejJ/kdZJSAMEYdZn/do=,iv:jxhzpRpAr7vPtLfW0jur2U2p/maz2Bdlk6Wy2ak1S/w=,tag:KkQ4w0CYzhzCPeROeTP16w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
