apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  #ENC[AES256_GCM,data:C4qxKdQ76SdUrEIWN9oJSNTVVEC0OQ==,iv:pa8d6MExopE+PNNpY091SKcRjF1Xcu3oR90c1EnzP1A=,tag:m76jb3tyHKUGNkQgUXNV4w==,type:comment]
  #ENC[AES256_GCM,data:Ydjmweq+XBrDfwPSBazgsBImELTm5+iW6Rg=,iv:PXyOlf4GdCy65CyhNU1wMtYasWJrizptbxPrZPPYskI=,tag:ddfR9LbrLSV9U2H8YyGuZw==,type:comment]
  username: ENC[AES256_GCM,data:cy+2,iv:02wy+moEx67w5XTWy47TV3YHmRlp52XMbuEy0s1iHAI=,tag:I86/QJ9zaEbpsMhdb4K2+A==,type:str]
  password: ENC[AES256_GCM,data:75Evgg==,iv:xGWmOVc96NO2fSWbBaaJ2karQ1pH7Z4CvLd1KjNHuBY=,tag:ip5HymD4bss1sv6RgMfDPg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TUxWVzhmV2ZFSHRjRENY
        Wkh1dVJ4RjVnazJvd1pSMFkwRDdqYW1rdzNZCk5raHI2ZEdUYlR1OUs2NHBqdStn
        b3BkbU1xT1ZvMFpOMk5oME5iU1plaWMKLS0tIFVhVmhFSTdKQVlXZnlKa0JmWkVK
        V3NpTW9tM29SazdIcVIyYmNWbHh6V1kKfH9Ni9EMYtn54RUEtzXatnSGGgdQX94n
        GjxPzx2iENb2Z01kSycVm5yBnl+BLUpe1dCVeCgHyMwLw+MfnmaelQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T19:53:39Z"
  mac: ENC[AES256_GCM,data:BlGraXswqeDSK0mg5Xl60yKckyEO746+k6cS5Kx6VGKsKskXKWYVfmgBHWTgJiyV/rezs9h6xqN5tGWEQE8SEnXCTZxkvWhcFXVMTCOjJ//3YESB3BuH0WscrwTxeNcx6ha70IPlMbpHty4EurO3j/bTYgBCSYmhMP3bK8iAgbU=,iv:s/9cVSvid25xRzGRzw/kO7fT2DoQM/uGVYJ8EmznVMk=,tag:sz9HrZ3cO+lQwMs71xnB+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
