apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  #ENC[AES256_GCM,data:QNHwdhFzO6qVwWEKojRGmZLNymLOuw==,iv:7G/+rcOUm83cLgVJnFBFsv6NoZDIqwnN1/9DXW14MbE=,tag:gvWkJTK4Cjcl6to03jc8Tg==,type:comment]
  #ENC[AES256_GCM,data:4e7XWdF+s6cnjbhZwXXeGni/XZTVPD7HEwo=,iv:X6yUlRXAtf7zt1htFft7iPyicWTLdEcnIfYwVHOclWM=,tag:jAePfLbztT386OEv+s2A8g==,type:comment]
  username: ENC[AES256_GCM,data:vym1hdEGCPI=,iv:yaZJEAwvB5KYpl4guwwaLyTWpQO7Vw0EguT9bfl4B2s=,tag:cX/rn9cHOsF/q0suF4BNnA==,type:str]
  password: ENC[AES256_GCM,data:dDNjE4uzfTg=,iv:/T9Yk6y0UUshPYisWeFi+BjFAm+BibHOlvp0t056uMQ=,tag:Lx7/k5dw8Z2LSHKZoaHhbQ==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV2FxQjBpZGdMZTJleDQw
        bTdRRXZ6UXpvZjZiWEVNb3hQVFhvMHFzVUZzClpwbWVFSW1ISXp6d1VTSjRYZG8w
        MTh6VE53RldZL2hsS25nSE9ONkh3RXMKLS0tIG5sd2VNVVMxY285RDVMU3kxWGRX
        MWp3UmZSUE85aGVXRzl3V2hCbW14dmsK6l3i/2aMKJ7/IDs8QZ3eylsbO382V/Pa
        /Atbf9FLF/jZYnxKGJXzXrAQaU7K+FwdyDCtUZsyHzmuuDJpPOh9YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T18:28:54Z"
  mac: ENC[AES256_GCM,data:hkfZMMW9CTdAdYfk/FgfCWTaSiptt4FKEH/HES7r90b/Mc2lUs9XAlkNFMmFsjA7GO/llKmRtUXoW2i2en7xm5qI7KRrPlkUTRtFCSwnDt/4qxvE4BcgIBGYUMwyzRl4Uo9zZR0trjtvwn4w/JsPmeXU+UXisVo6BQ6ICgCJcII=,iv:jDheKDOtVd+zeIhPnWzSHrJTd+EEo13OyvsrN+jgHRY=,tag:362SUahYni2AS4SSGAiXLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
