# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: adguard-dns-secret
stringData:
  ADGUARD_PASSWORD: ENC[AES256_GCM,data:3rWZKzF+gBU=,iv:h+nXKYwoMN0y4KQnMWfetzDRXK3DPX9YGu2/FZ92OM4=,tag:ZOCqZGTzteE9hwyPPIoKSA==,type:str]
  ADGUARD_URL: ENC[AES256_GCM,data:mbD82dVSjTfQhM8IgGjOl7TOLpWYABvk16XxK3JIC2nCWM4nSt0fwczRHxvGYF4O,iv:PwXSrSMAIOIykwqinCRCHQ0H4zMmRJNk11AeyG6pFyA=,tag:NFcaKi9x5bD/Rp8HNqV4vA==,type:str]
  ADGUARD_USER: ENC[AES256_GCM,data:TvxNtVyu,iv:vYoU48dWxjsZl5MQsnIJYHkciuZGv5uRfZz1TsngOsE=,tag:v8j4CoOs54Z62RekG77ymw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXhaaTJ3QitXdGVpeVo2
        V2lLTXpNZjc0ekFHY2RxTnhPZ2JCY1BLTkE4CithSVRnZ2ppaUgzS201REcwUkU0
        UlVpTnpab3ZmZlF2eWRuWWIrT2p0dDAKLS0tIEs1ejNDZitXY1lRSHdHY3k3a2Fl
        bHlJaWxnR0RaL1RnOFE3UWZydkRWTUUK0ReTXKVUfgEVHSscfCa6CKF5WG7qSjeA
        llWP2m2Ap++Joaw7CDBWi+LBnT22juzrbberAJyAFyh15isZ1SYtCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T15:01:49Z"
  mac: ENC[AES256_GCM,data:bprUltMHJO3wBd2dxNeAPgDNjzQVFtsat+1DWEXOCHadEFcwNlu0ldnhGbi3VcbwaulbPCn2g2PicNqK2Z3ikzVkBJ3oGBgvbLKwhcBdEZXpBqvlauH4VlcuYsItSpbfsy7hp82VW0MDmv1kqbxe0YOMbuBMmlM4kd3fRfcYZy4=,iv:MuDrVLhRJQT84+L/kjZikXIRU75OHpc9XM1aoTDVTys=,tag:J29xFKtI+9dwJbl+3jnzqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
