# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name immich-server
  namespace: &namespace media
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
  components:
    - ../../../../components/keda/nfs-scaler
  postBuild:
    substitute:
      APP: *name
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  path: ./kubernetes/apps/media/immich/server
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: immich-database
      namespace: media
    - name: rediscluster-ot-standalone
      namespace: database
    - name: keda
      namespace: observability
  targetNamespace: *namespace
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name immich-machine-learning
  namespace: &namespace media
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
  components:
    - ../../../../components/keda/nfs-scaler
  postBuild:
    substitute:
      APP_NAME: *name
  path: ./kubernetes/apps/media/immich/machine-learning/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: immich-server
      namespace: media
    - name: keda
      namespace: observability
  targetNamespace: *namespace
