# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-web-automated
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: volsync
      namespace: volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/calibre/calibre-web-automated
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nfs-scaler
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app calibre-downloader
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: calibre-web-automated
      namespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/calibre/calibre-downloader
  components:
    - ../../../../components/keda/nfs-scaler
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
