# yaml-language-server: $schema=https://schemas.budimanjojo.com/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name immich-database
spec:
  postgresVersion: 16
  image: ghcr.io/budimanjojo/crunchy-postgres-vectorchord:17-0.4.3@sha256:76ed3fd67179d66b8c5a56154d4714680da5557e4507160f10a9aece42465823
  config:
    parameters:
      shared_preload_libraries: vchord.so
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - host all all all md5
  databaseInitSQL:
    name: immich-database-init-sql
    key: init.sql
  instances:
    - name: instance
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      walVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
  users:
    - name: immich
      databases:
        - immich
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      restore:
        enabled: true
        repoName: repo1
        options:
          - --set 20251109-010001F_20251110-010001I
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        archive-push-queue-max: 4GiB
      repos:
        - name: repo1
          schedules:
            full: 0 1 * * 0
            incremental: 0 1 * * 1-6
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 5Gi
              storageClassName: nfs-csi
