apiVersion: v1
kind: Secret
metadata:
  name: lubelog-secret
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5U2uM9illQ==,iv:BdTltJ0MM5E42XyU4dbCqhV+omiwmA4H3wsMY7dT0uQ=,tag:vne2J4vOqJWY/0V1uEhoQQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4LRdC/uL+yWG6p9Rh5CcnDx6ob0nW2z32JoqzunD+iXHYjrXMxg=,iv:39HYFamX/vRYTO2AXgNOhRmjwmRcRz5m6OZNXMWlAcs=,tag:tITawCAWJM0TVJzs0T6NDw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:N/NnQvqGOw==,iv:npdY31Hnwg3ueIlgEokYTTdOoUEEdqgJnZBQJchiOcY=,tag:lgoQsnvSj22THLUTyzPiBQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:KsGXEASWVw==,iv:a5/sCfylS1vOWiVwAqoZW6x0CwgXVBp7OKRgMLqxCO4=,tag:ttDNJtAAtV/8Q94Mk2NX6A==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:uzLj45nFvjA=,iv:ypknhz9PP5IsnDwzhNoobHnFfkm6b3yuxi5ugkFnV4Q=,tag:hfzIcuOpU6uzYo9enVMoNQ==,type:str]
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:LZi3bXJjtc0fa7ZtJ3Z7jGLmM7luj71jG5FnDTZgnbOIiqsydqpYxlpykdoVva7k2DvXMFLmuzPmRcNl//LpdF/lPqqzKC6MqgMP/meFClCM4uVYl3bAIpitSYd6RGWOud3E,iv:eQ5J0cQZxmYpi60I5JO4jXsfYVNhdwIi8+myJtkseP4=,tag:JU5UhQnuVj8b0QocvgI8Ww==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUmk1eTNsQWFzcjVQR3Yw
        eXR1NTN0c0pDaHNZNGtGYXlZbmF5NEUvT1h3ClJNbDZkVmt2UWsrYjZvR0pnY0N3
        SkxmeElZMUlPdVJxUGp2SzdxQTFTNG8KLS0tIGVXR2JManFCWk4zR2RYdkQ1V0Q5
        Q1U2VFJxR2wxWWxrbWJYRCt6OE56WkUK2SZyZsoocK05h21rzsY04duwp2zT0ueZ
        pfVz7bAop0bbbPbL2mvVJTxyr3x7ImZuKdc9M3k8DKP83wNlW1INqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T12:59:57Z"
  mac: ENC[AES256_GCM,data:f7Ly9qM3qSWPanvrhfnhLWRru3iaY4Ps37ty8ulLTBinFeyDxhs1nFtdqJYjfe2/XleT/MTxqk7afrmPHCKDdG32ZV9AGcMkdYNjStSKoummKTgnmYHBA220kk7lGHu4HVa90Z732uUR955dyFku6Jijj7yO90zElHP3iuFGTtY=,iv:fj01twsrRkzOGzC/1udu1EvNw1atU3WI1EqNq8JMQ0U=,tag:BtPCqMBUg/SbbJa6LipW6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
