clusterName: heim
talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"
endpoint: https://192.168.1.8:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.8"
additionalMachineCertSans: *sans
clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]
# Disable built-in CNI to use Cilium
cniConfig:
  name: none
nodes:
  - hostname: "hp-0"
    ipAddress: "192.168.1.20"
    installDiskSelector:
      model: PNY 250GB SATA S
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:22:e2:17:5a:5a"
        dhcp: true
        mtu: 1500
        vip:
          ip: "192.168.1.8"
  - hostname: "hp-1"
    ipAddress: "192.168.1.21"
    installDiskSelector:
      model: PNY 250GB SATA S
    machineSpec:
      secureboot: false
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "38:22:e2:1a:92:09"
        dhcp: true
        mtu: 1500
        vip:
          ip: "192.168.1.8"
  - hostname: "hp-2"
    ipAddress: "192.168.1.22"
    installDiskSelector:
      model: KXG50ZNV256G TOSHIBA
    machineSpec:
      secureboot: false
    controlPlane: true
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f8:b4:6a:a2:f6:2b"
        dhcp: true
        mtu: 1500
        vip:
          ip: "192.168.1.8"
  - hostname: "hp-3"
    ipAddress: "192.168.1.23"
    installDiskSelector:
      model: M4-CT256M4SSD3
    machineSpec:
      secureboot: false
    controlPlane: false
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "false"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ec:a8:6b:f4:58:5b"
        dhcp: true
        mtu: 1500
# Global patches
patches:
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options:
              - rbind
              - rshared
              - rw
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-dns.yaml"
# Controller patches
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - -selinux
        - apparmor=0
        - init_on_alloc=0
        - init_on_free=0
        - mitigations=off
        - net.ifnames=0
        - security=
        - talos.auditd.disabled=1
        - i915.enable_guc=2 # Meteor Lake CPU & Intel iGPU
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          #- siderolabs/nfsrahead
          - siderolabs/i915 # Intel iGPU
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
worker:
  schematic:
    customization:
      extraKernelArgs:
        - -selinux
        - apparmor=0
        - init_on_alloc=0
        - init_on_free=0
        - mitigations=off
        - net.ifnames=0
        - security=none
        - talos.auditd.disabled=1
