apiVersion: v1
kind: Secret
metadata:
  name: paperless
stringData:
  #ENC[AES256_GCM,data:4u+83cN4vU0=,iv:Ba5xRVsK/hYCA39wGe0/j1vgJ5RnxYZYyjMzHavCttI=,tag:m0T+2RFBaWczlOI9H8+S7w==,type:comment]
  SECRET_KEY: ENC[AES256_GCM,data:uKAoKN29Iso1voorSkOb2xzTZXspkJXvKwQWbkRx6kMwCEcPt0t4HY33eZeFlQxI1PY=,iv:88ZEw45nS0pCMrcLqBIQEncoX2ctAoAzNHDTDjFGgQw=,tag:X7oWzExdnmrA5LftFs5Ntw==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:+kBe,iv:XZ8fA1nTWDisprKqzUjZ92p+uhbKDb0rDd5Xf3+FQFM=,tag:wyxgU6KdSuQzFt0D75qV0A==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:iMrK5Q==,iv:kCyynzPGdF+e4BB/Q4TnAV61ipfk83AZ+IjVHCjBDd0=,tag:3BvMtPBuk2QLieAhyDbu0A==,type:str]
  PAPERLESS_DBNAME: ENC[AES256_GCM,data:6mJeFC1YQL9m,iv:MNFf3TkNoNn/vornKIurrXWkrAxIGJjwPqB2lyOrUsk=,tag:T60kSBY3oiH6tc0vzp3Zyw==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:5L1tzz+dLIlQ,iv:6TrpFKn7xGmKJ9MfwvAROjKpOBDSUWtMfMiTPhe1L90=,tag:eldIdVX97tniWT6DPfD8vg==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:sJ7xgaGHcdxS,iv:zM6CDcnCCK57PBC56l3JsLixOxoDvxuYbDBKCawULtY=,tag:4quP9h6opio00B7toUsYwg==,type:str]
  PAPERLESS_DBHOST: ENC[AES256_GCM,data:kJq1F4XCG6MBy6KX9nsEidf0pyIyG1+/RbJ3Ql6KmsNLv2jQA+A=,iv:bRjYenZVNhmSVNrrklSaBIC0yhse+dO+2nfFHjWIKfs=,tag:YR83MsIXoN3y0C7hPdBcyQ==,type:str]
  #ENC[AES256_GCM,data:heNyJGFfABvbrHl/IYE=,iv:vTiLiBqJVGkrlMmabBwCOl1L0L3mNS44zZljvEkCf4Y=,tag:9AHDRufe1tY/D+LZJ8Zzzw==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WXEr28okTQp8,iv:uTM40XUZQYVRi00k7ri2SOGzsKwvGZCzODE16Xjaylg=,tag:GBuyXpbxq1oTvjcvv7iDTw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BdnqzVW19bHQX77G4gjUkuhvQW302iRUZ5lyP8cQVE6bHTXdpdI=,iv:bA3jRbNbLqqDqUrwZ2ljjuihsAkfci7iQINMG28xpJk=,tag:1gIkXlJop9lat5OfdDbj/Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:KI4hYx34ilHA,iv:jQ2OeRZCHAlvnVh5SiTcULdrQgwM1uOjegYr8comrcc=,tag:buR6gZGqfiCpgQ7pYUZRFw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:xQs9ldETpKtP,iv:lDdIlkzqsuI2eiF96BBnK36OdGuFX3wmtDhwq+KgNsc=,tag:nWoelTfeMS31I6lfr/87Yg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:XykqqgJ5zEE=,iv:/kldOi0cAQWmPv3IWsx8Pr50+DtLAIH+Q2iB+3yMJGI=,tag:UABCEivYfveeReQ81KnpKw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVzA4R1NmUHZoaC9ZSnJ0
        WXErV0R2UTZyVElhK01EZlArOUQrejFxQVZVClJ0LzE0REVQQ2s2MmRyQVhlUTVT
        azJQTEVxMlZCZWplWm5hODlrWjNPT3cKLS0tIGRXZWY3cmxkVWU5N2VodnlKK0o4
        dWtDSm5hS3doVlZydkY0RzhpeFZaSTAK9hauYPnnDmT+oQFzBKdvOnwKmHZ6HOD/
        zBk72nxThLy6f37WB4N/ean5XtYHx5mH/YD3qylKAJsXs5ESHsHx/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T19:48:02Z"
  mac: ENC[AES256_GCM,data:y/PYM1VnqQYqvBohEBUSF3qO5j8PGGu288ikJUwfTXTfCAKiTf1gzsS79ab622OkOTGBkUd1EbfRtOWiMBs5TE0p4h+7KuDTVns5Ea/0Maf8OzIxdlalOn4Ap0qWIWhh/ThcW3EZsBabkJQsYRdnvWdkDKCU8ipKxBMJKZFvHdc=,iv:zKjFgRRDvsiI7Yr4JBspU4HjAol73vu2GtWe2t5dUsc=,tag:5p98Bm1BGFnmMmgcqWzXKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
