apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:l6CHFwbvPJeBjemEoDmAT2P+DLn1clqtDal6vJ0OdbhifuEYOEw=,iv:Z7rO62oxPNWQN9jZP+hlxp/Ty3GiQZ3cE3h6Dtqu/mo=,tag:/Vh31q8b4VYlDJoDiJUaqA==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:BBCgH3Qyoc8=,iv:FYnWtsSLYsS5vnArExI6/595qWu1UYf4eV1lFKZQ2qQ=,tag:ohKSHg3zcdAwjDha0MaowQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:kexe12Ipt+Y=,iv:2C5MjYI6ojwCLBqRf6gR/Ax0OYAUx/W7Y1iacIg0gwY=,tag:j/EwimzOxHqpUgw6BI6zxQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:yV+gbg==,iv:O+EvzmeWTiqn0tp9uWhoFJ7KCIR3X697CZojuAuZVDU=,tag:cWrkGc8npmFvQlETAxlkDw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOElKTkg5bHFBbTIyOWN2
        YWZTSnRNTW43UFd3ZDJoN1QrN3VOSkc1UTF3CnpnR0pIbk1ZQ2FEVGFpWVozWXlK
        QTlYaU5WTUNmbkhsRVdhaitONEFTYTAKLS0tIFlFSUhqTm9LRDRiMVBuYVBUUlQr
        OEE3UTFYMms0dWN6WS9XMHZRWEVPWE0KjP+LWUYaHZ8mPbfJRB6rorjefyJW5AbF
        l1ZBrSz2AaLQoT2CBB2lBmskPqwsHSsr/i+V4kXF9dxFprvqOw1KGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T12:41:03Z"
  mac: ENC[AES256_GCM,data:OT81SVvE6LrvPBtfCgUjWtUkkmSvfDh1qVQNjD/Jzhq1A7ZngINyqEHlhE6f3z22E5j5J/yQPuNrUjeAX8aqUS+6hsleyZVv4zNL1ctoTDx3B/zDeGzSfKw/olT+iraPvpl1l9P7IdZjY8H3ZSKkzRNLJTJg6umL3rCeFID54ws=,iv:rGYTuwNn2unjqJmzXlD0WWJYFYsjDHWnvx4EWI7fYfI=,tag:WiZ39/IdWjK0S9GBqqDQTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret-immich
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:Z5sIFI6jUMnMKI0DNoJPEy9TX3vsrpXwqEOfXNTjgO6X+r4A,iv:5wv6HIsConNuThC5q2UgFrqTas7QunDKT2Zi8az/kpc=,tag:1XASnm+ScMgsiLg4mIfNMw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:wD4luwU3EX8=,iv:E/TbrhxvCrIwt+RKVoSZiDEROMMaJfuY6iD3XCPmZNM=,tag:kfCLKb5hzZzMh8JZZEucDQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:WrITa9ph1y8=,iv:/i5v3miMQAGuzRiWIbG0/Jklw4+26aYIcS6WGQ+qJOI=,tag:wNgEGC3CQOls+2cVPEhuLg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:NdIo/A==,iv:6bdM557LXu46eH6o30FrOulrs2LHXCBTT1e0zqqGsxo=,tag:YAP5YZmhevbYWnq4XXFnFw==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOElKTkg5bHFBbTIyOWN2
        YWZTSnRNTW43UFd3ZDJoN1QrN3VOSkc1UTF3CnpnR0pIbk1ZQ2FEVGFpWVozWXlK
        QTlYaU5WTUNmbkhsRVdhaitONEFTYTAKLS0tIFlFSUhqTm9LRDRiMVBuYVBUUlQr
        OEE3UTFYMms0dWN6WS9XMHZRWEVPWE0KjP+LWUYaHZ8mPbfJRB6rorjefyJW5AbF
        l1ZBrSz2AaLQoT2CBB2lBmskPqwsHSsr/i+V4kXF9dxFprvqOw1KGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T12:41:03Z"
  mac: ENC[AES256_GCM,data:OT81SVvE6LrvPBtfCgUjWtUkkmSvfDh1qVQNjD/Jzhq1A7ZngINyqEHlhE6f3z22E5j5J/yQPuNrUjeAX8aqUS+6hsleyZVv4zNL1ctoTDx3B/zDeGzSfKw/olT+iraPvpl1l9P7IdZjY8H3ZSKkzRNLJTJg6umL3rCeFID54ws=,iv:rGYTuwNn2unjqJmzXlD0WWJYFYsjDHWnvx4EWI7fYfI=,tag:WiZ39/IdWjK0S9GBqqDQTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
