apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret
spec:
  data:
    POSTGRES_HOST: ENC[AES256_GCM,data:C3X+K4Y5D2o7QdE7JyGGk6LdT12oOp1h/6J/26jGP8iZqBUUa8M=,iv:+cxHjve5TW0w6Ng4L+FAkHHEYxm9hPUv1eP2tndZJsU=,tag:lsIk+zHIo8HIvk5+EWKuIA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:X1srzpx6Lck=,iv:vyATPr058oXUP1ykkqcp6wXJTsdnq8w3EAQkPKpFryo=,tag:PzairIVpdJpiTPHCdPqRKg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0nspn7yKEbY=,iv:N22UK7pVTny27DD/y4pJwJDwtGvKyGBNdfGKXq+jO34=,tag:NX3nB9BozPziZO39WDG/RA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:kHL6Sg==,iv:sCjJ4v4iWqYpKbaOCc2prf7ZjTQ4LXv8k41P5lLB6Fg=,tag:LHeW/Emo5pSDT5W2RwBvow==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQi9wU1l5NmVGT0ViTkFM
        Y20vdExqTDZzRjNLWHp4cUllU3ZHT3lWTUJZCjRPcmlKbnM3TnpXdjFFYlkvOFFj
        ZWU4T053NVQ4QnoydytEWTNseTNaQkUKLS0tIDVFK20xcDlobFJVZ1JRUFBabFVV
        czBoS2lKd1ZXbWQ4ZXVybVdiazNQemMK39QiSvPq87VEhtpE53Hg3l5Jx/DZQOEv
        ISgD7iHW1jrxb8iQPfVNSBQQwjWO5Iw9AiHgyhlBO2VkHnKnvpXLIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T18:29:04Z"
  mac: ENC[AES256_GCM,data:Spn3v1lXKei1j56YYMKPeJnuILwK/xaGF60k2d4rKEM8XXf5HxWd5HKn2ZYjtosXA41I+2QuDZjetmxlv6+qEx01BlW3zXKS/MJjzZgXAnUcC0/a+bqB3DTrdb25HmhwuYAbrRKQgmyRvHPK9x67L+cLKn45+tNm4DB9HruIhGE=,iv:JImSv88YQbosp6J9BCZxGqGnn8awXDrR6pXnr91pLPU=,tag:NvuhoPJSo7GTvMZ7MqgVYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
