apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret
spec:
  data:
    POSTGRES_HOST: ENC[AES256_GCM,data:6TZ/nVAi8lIN+TZDyR8RZUMb58o8Ia7ZjbMCMCLAIiSipxOgENE=,iv:z8HTDHGUJYZ+34UOmc1WlZTioK5aQWiuZHjJ3iiKfFc=,tag:QwGJvfr/XMShIKjH6dUshg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:xr4v,iv:xaLFZGFk2mAedG71wGsKuXMRTJXZoi743f9+R4IEY+o=,tag:aMTmXz2yvKh6YgmX2QzMpA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mjLVdA==,iv:Mss7Db+VX7WbFOMP1t3SlTN+a4saHEt1jb4YKqOWcUY=,tag:RgvzDy2uFHareOLVEJKidQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:3OZ5QA==,iv:Mg7dwYsUl0epBVjEodqJlxTtp/0Io0vog9NUtC6szAQ=,tag:0+MvW+LuULww7Eve7S8+Jg==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcGZkUWVheXpKL1hxZkkv
        VWp5MzVhZW5PU1A0OFJnTVpCclVpNzl5dFNnCjg0TkRiSklzT0RvVFhjZ0xWbVMv
        ZmtjU3RuRnYrS1NTcGVKSjE5d1pJcnMKLS0tIHNoM244cXBhd092Y29JOENXSnhq
        UitXQXdVeDlDd0YzdGpkMmV2NVc2VGcKLFIatSliYwlpBA/+BcmgHtP5bg9s2bgv
        V8XrBn3BKij8PBRO929tCya8UX9IPbA+w2oU+B50ApGalE03pga7UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-13T20:02:26Z"
  mac: ENC[AES256_GCM,data:rjkNWxNIJOOXqrwhR3bkMiEblc0WRNMmOCn0+3SYmBHAVlrtpuv0zKUqoxY/FCVPb0ohjhY4XD1MNxsKOYBnsR/VehLPYBD3XCJX+yGgGfBkJczSYn40nZwHuZCgpKzpdOC4X1sOg0YB1aAhFUbYVW8+5QhlVQAAAzq9rzslbKw=,iv:7Y481QBQdQH/drFwcEsNBtQ6vCmbWeDfbgB+y9pZ8W4=,tag:6FBSI9NlPUkjDDju3TlmQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
