apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-postgres17-pgdump-secret
stringData:
  POSTGRES_HOST: ENC[AES256_GCM,data:/OZIxO6Sa+kdRySe8D06Tag77MoxWTb13RXAKJz2r0w+vkuUDm4=,iv:RGp0PoMZbdPlw8fEakw0FGol6+pFVR+yTqXc706K0r8=,tag:0z7zldzrhS93VbHCBJRSNg==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:D/6AWtlLzXc=,iv:yJz7dD59gNGFl+bkMllDMkPfdhRRqO6qqGmKH5id7AA=,tag:Mlxq8vJk6V7VrmzqxnTSXg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:4agSHN+Gjtk=,iv:GSd141RDys8Co2U1/qp5Ev8EnxQkgBOXBZwPSCzABm4=,tag:JZsIkWD5C52896WvIomHRA==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:ZKLLiQ==,iv:b0Lv3vomL8sQydv/2FKssa8DF4Y8IlFNB2j8KjoLYpw=,tag:zdtev05+y6i7kZRdpwjqBA==,type:str]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ21GdkVkS3ZzSkpPR083
        YTRjWndCdHM3R25aM3U3Tzc2dlVRWjUzLzNrCmdXdTl2elBOdVVuejE1OVAxR2h2
        TnJ5OTBMOEVSNUNTMnYyemVkcXhEb3cKLS0tIDh2NVExZzBhYVg3aFBiUFJ6T2Zz
        eXVFUVhPa3NXdElBN3kwclBXSWlSeEEKzBnwzNWQ0AI5EM+7cBd/ZQSTl6VQaEFI
        UYWj+PjQveI8zNGey0nHRYilvMhvRdTVW01AGSJ2mRTgdaXdffXmfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:04:22Z"
  mac: ENC[AES256_GCM,data:athISV8gvQNX1q+ua5IRPOqd8+s21fE6kJPEI+GQGirH9sA65PHH0f+SQ1o+C6G33sGyA1nq0Bv+uyAPJjeylWd5EltX6kPUcmCncglyxEaGjZ5jHqxhoqIa1zJloP/i21m2Z7FeOBWMyerS3dixPkBjOrzXHzc9xU/ZPAiwg1c=,iv:W3U+eSGGezho0J+1iFoF8rlvIuWcKpNZLfaiXrMTldY=,tag:VV3HErQKuFwv1g8L+yWy7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
