# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
type: Opaque
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:tfb3moRmeP2GaZOvFc1Y,iv:6mRFg2pCtsQoR237iu+cPjoX8GcPb8Hfs/+r7O1v8kw=,tag:4aEH7Yu449B+RwIu8cg+Lw==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:ZPS3OMrPhok=,iv:wzyCykRf8rmZoz83Qsxj6glaQBdhokG9CB97LyUezYA=,tag:YgGOgjWkWoZDusoc7BTCBQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:y3BGerg4UPk=,iv:CQnLpLnIoswV4g4pobtPkFJf1wojmPn9DwSTb4dTr9I=,tag:OD+zr0/PDRjawyqWjvgK/A==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:3lpH7UeYh0iNQoTPfxeEIgnHB1HdRCFj6jEmIdQhc6LwDCRX,iv:zhx22vY0gouPKpR6NPsio08zf+X4vtmhVVnyS8Tw6iw=,tag:LsNE4tVwaGZl1gZvW/VhAQ==,type:str]
  DB_URL: ENC[AES256_GCM,data:VY1hnz7I/DIuH14/Io2pVgcJkOlUE1ypw4CbC/4g6/vNmdh7Ru0Fno2ZKlHHPN6sSq34LBqo5XG5AkJN9U8Pg1pFgi9TzAJjTKVor/pTZpY4Qyg4gyCPl+KzFhQKVb6WvdJDmpREPsLvbmK43ppImVg=,iv:fvbx9GUTxV/GIRXNrFSE+W2VoO9sRQFff6DK+r7UX0M=,tag:USC7lq9KkmZTRIdFEbHNBw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:uj4Skg==,iv:ElhwJ2swT5wbsynoIMfN5AHJSPRfOj5U3r+Lz214a7s=,tag:PAuByMuhd4LGHgglN+EiWQ==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:2lBgxvgO,iv:wp9VZ/F64SSH+qS642kE3x9CFoUpntuJqvbuwgIbdBA=,tag:XD/Xv5ybjsO/YKGL5fBtZw==,type:str]
  POSTGRES_ENABLED: ENC[AES256_GCM,data:BwpVhQ==,iv:i9RBplrau73EJfF+2MOQBpnNY8EHM6/CcBVTE4wriWk=,tag:lJgQ4wY+B2LFMjJjse5rrg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:QW8qHzF3,iv:Ty/oRbRgtdoyg6Fr5MfeYSP/UaswqT6v8zJKxN68gM8=,tag:NrCApz4RrfHW625J/zEJXA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7Jcm3n6ljq3OMmuT1IWRSfcbBT0VpYPzZ1TYN7XVPMbt18Nw,iv:iEUQT100lkAaOSbF765yR5b/Gdw5EJB2hactNgBTBTs=,tag:gZevWu8uN0s3sxjw8sK3Eg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:TTHdIWhp,iv:E+o8Wq5la7qV+azDBCDYI1cbtyCZvlaECdJODmexhzI=,tag:PwD385UEgD18701wd8fXsQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0asQ8Tra,iv:bOCe6ttsaHxzW4d2kDb2Q6ubIbrLdaK4GXyPe70+4P4=,tag:lHnqoUMDdfLTPSZzBzU4mg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GIJKBoUeaYQ=,iv:6170yw6eNeiMxSic6QkxC8U4kpWn9E49ktK9p4kqOro=,tag:JOn4O+fwoi31uwltjFKG3A==,type:str]
  #ENC[AES256_GCM,data:WQFahQrsEAGR5olr,iv:26VsTBeaMh5q5ogsHN+ebUpRKbEWJiucyCI/mmVahu4=,tag:ymr2N2JeubocYNqVg12YOQ==,type:comment]
  #ENC[AES256_GCM,data:TjAA9R8aOIJSM2170enjzN3BUQ==,iv:w46qH659up4+MzdGQ9Vmq4TZPdTLWrA+uMG7UJUi3Vg=,tag:wVe6W/SLA8tG2aMFQrA08A==,type:comment]
sops:
  age:
    - recipient: age1yw4z4shdemtcqwee8d7uxl7slw9mertg6dulakpup5nca66lwysqpkpvuu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVmZva3o1K0szdmxMYVpu
        czZaSU1vMDNQRFdHRGUwTk8zT0lGT2JkeWlvCjk4ZEQ1VFkyc3lTR2ZqU0hyWVBW
        czE5c3VvWHBNUVE4bG5YenJXeUlxd2sKLS0tIDg2eEI5ZlZNaDJEWmhDNEZ0bzgz
        R0lWdktOZ1hmTENFemRyakpaRG1XWFEKAs5hV0IrIbwGgVqrK5mvC5AVkmxcyarK
        YooIi/PsKN7HDADxlxsruDNpGq+mWMuuuSLKh3ZCQYZ6VRQlrzxN0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T20:22:07Z"
  mac: ENC[AES256_GCM,data:DXf34jNmncS1WQ3hiPObYOrpBLE0HyQqvB+FeN1HjbkLtwKAlFKhI5fbNpcqi+YvdexFd80zLgsMssjfuow/LQ7w9W5yYRp0M7yMXEB0kvEaybOGRM+igAPLGstM10eq8P1txHNqt5rc920knkzEJRK7figBJGHnQverL6hzmtI=,iv:MwMbk4w0bZR50a+H4zRfH6LpXd4rozX5H9z0m9vjefo=,tag:lq9CIJxT4FYtEK05yXdRrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
